name: calendar2
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0-83.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  table_calendar: ^3.0.9
  font_awesome_flutter: ^10.4.0
  firebase_core: ^2.12.0
  firebase_auth: ^4.6.0
  cloud_firestore: ^4.7.0
  firebase_storage: ^11.2.0
  provider: ^6.0.5
  fluttertoast: ^8.2.1
  http: ^0.13.6
  image_picker: ^0.8.7+5
  image_cropper: ^4.0.1
  get: ^4.6.5
  flutter_local_notifications: ^9.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
