// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfpLTqKBQM_1ziW7hts4VtisgjGhvs3H4',
    appId: '1:50781357906:web:f0936259c9f4f9b71c9c8b',
    messagingSenderId: '50781357906',
    projectId: 'calendar-a00896',
    authDomain: 'calendar-a00896.firebaseapp.com',
    storageBucket: 'calendar-a00896.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdbK2lwuECi34HynbK661BCcSwKH_ZzXE',
    appId: '1:50781357906:android:f35d14f2061241221c9c8b',
    messagingSenderId: '50781357906',
    projectId: 'calendar-a00896',
    storageBucket: 'calendar-a00896.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbtPP2sQeUuH1CkvYbAKMEodCAuKBWiUw',
    appId: '1:50781357906:ios:14ba55fed20cda5a1c9c8b',
    messagingSenderId: '50781357906',
    projectId: 'calendar-a00896',
    storageBucket: 'calendar-a00896.appspot.com',
    iosClientId: '50781357906-8l02iran4076cab8bg2gdt6qihp9vjl5.apps.googleusercontent.com',
    iosBundleId: 'com.example.calendar2',
  );
}
